/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;


import Encapsulamiento.Usuario;
import Negocios.UserController;
import javax.swing.JOptionPane;

/**
 *
 * @author jmcito
 */
public class LoginUserForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginUserForm
     */
    public LoginUserForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuarioTxt = new javax.swing.JTextField();
        contrasenaTxt = new javax.swing.JPasswordField();
        ingresarBtn = new javax.swing.JButton();
        registrarBtn = new javax.swing.JButton();
        titlelbl = new javax.swing.JLabel();
        usrLbl = new javax.swing.JLabel();
        cntrLbl = new javax.swing.JLabel();
        nuevoUsrLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Expedientes CIJ");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(usuarioTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 68, 211, -1));
        getContentPane().add(contrasenaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 107, 211, -1));

        ingresarBtn.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        ingresarBtn.setText("Ingresar");
        ingresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ingresarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 146, 108, -1));

        registrarBtn.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        registrarBtn.setText("Registrarse");
        registrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(registrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 106, -1));

        titlelbl.setText("Expedientes Centros De Integracion Juvenil");
        getContentPane().add(titlelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 12, -1, -1));

        usrLbl.setText("Usuario");
        getContentPane().add(usrLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 73, -1, -1));

        cntrLbl.setText("Contraseña");
        getContentPane().add(cntrLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 112, -1, -1));

        nuevoUsrLbl.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        nuevoUsrLbl.setText("¿No tienes cuenta de Usuario?");
        getContentPane().add(nuevoUsrLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarBtnActionPerformed
      
       Usuario user=new Usuario();
        if (!(usuarioTxt.getText().isEmpty() || contrasenaTxt.getText().isEmpty())) {
            user.setUsuario(usuarioTxt.getText());
            user.setPassword(contrasenaTxt.getText());
            UserController acceso=new UserController();
            acceso.LoginAcceso(user);
            this.setVisible(false);
            
            
            
        }
        else{
            JOptionPane.showMessageDialog(null, "¡Llene los campos vacios!");
        }

    }//GEN-LAST:event_ingresarBtnActionPerformed

    private void registrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBtnActionPerformed
        RegisterUser registro=new RegisterUser();
        registro.setVisible(true);
    }//GEN-LAST:event_registrarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUserForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cntrLbl;
    private javax.swing.JPasswordField contrasenaTxt;
    private javax.swing.JButton ingresarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nuevoUsrLbl;
    private javax.swing.JButton registrarBtn;
    private javax.swing.JLabel titlelbl;
    private javax.swing.JLabel usrLbl;
    private javax.swing.JTextField usuarioTxt;
    // End of variables declaration//GEN-END:variables
}
