/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Encapsulamiento.Medico;
import Negocios.MedicoController;
import javax.swing.JOptionPane;


/**
 *
 * @author jmcito
 */
public class MedicoListIF extends javax.swing.JInternalFrame {

    /**
     * Creates new form MedicoListIF
     */
    MedicoController medicoList=new MedicoController();
    public MedicoListIF() {
        initComponents();
        medicoList.MostrarMedicos(medicoTable);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        medicoTable = new javax.swing.JTable();
        editarBtn = new javax.swing.JButton();
        actualizarBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        nombreLbl = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        especialidadLbl = new javax.swing.JLabel();
        especialidadTxt = new javax.swing.JTextField();
        telefonoLbl = new javax.swing.JLabel();
        telefonoTxt = new javax.swing.JTextField();
        emailLbl = new javax.swing.JLabel();
        descricpcionLbl = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        descripcionTxt = new javax.swing.JTextField();
        tituloLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Lista de Medicos");
        setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        medicoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(medicoTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 179, 662, 132));

        editarBtn.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        editarBtn.setText("Editar");
        editarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(editarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 85, -1));

        actualizarBtn.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        actualizarBtn.setText("Actualizar");
        actualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(actualizarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 100, -1));

        jButton3.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jButton3.setText("Eliminar");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 90, -1));

        nombreLbl.setForeground(new java.awt.Color(254, 254, 254));
        nombreLbl.setText("Nombre");
        getContentPane().add(nombreLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 52, -1, -1));
        getContentPane().add(nombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 47, 200, -1));

        especialidadLbl.setForeground(new java.awt.Color(254, 254, 254));
        especialidadLbl.setText("Especialidad");
        getContentPane().add(especialidadLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        getContentPane().add(especialidadTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 200, -1));

        telefonoLbl.setForeground(new java.awt.Color(254, 254, 254));
        telefonoLbl.setText("Telefono");
        getContentPane().add(telefonoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));
        getContentPane().add(telefonoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 200, -1));

        emailLbl.setForeground(new java.awt.Color(254, 254, 254));
        emailLbl.setText("Email");
        getContentPane().add(emailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        descricpcionLbl.setForeground(new java.awt.Color(254, 254, 254));
        descricpcionLbl.setText("Descripción");
        getContentPane().add(descricpcionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));
        getContentPane().add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 200, -1));
        getContentPane().add(descripcionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 200, -1));

        tituloLbl.setForeground(new java.awt.Color(254, 254, 254));
        tituloLbl.setText("Lista de Medicos");
        getContentPane().add(tituloLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 12, -1, -1));

        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBtnActionPerformed
        
        Medico actualizarM;
        actualizarM=obtenermedico();
        nombreTxt.setText(actualizarM.getNombre());
        especialidadTxt.setText(actualizarM.getEspecialidad());
        emailTxt.setText(actualizarM.getEmail());
        telefonoTxt.setText(actualizarM.getTelefono());
        descripcionTxt.setText(actualizarM.getDescripcion());
        
        
        
        
        
    }//GEN-LAST:event_editarBtnActionPerformed

    private Medico obtenermedico(){
        Medico update=null;
        int fila=medicoTable.getSelectedRow();
        if (fila>=0) {
            update=new Medico();
            update.setId(Integer.parseInt(String.valueOf(medicoTable.getValueAt(fila, 0))));
            update.setNombre(String.valueOf(medicoTable.getValueAt(fila, 1)));
            update.setEspecialidad(String.valueOf(medicoTable.getValueAt(fila, 2)));
            update.setEmail(String.valueOf(medicoTable.getValueAt(fila, 3)));
            update.setTelefono(String.valueOf(medicoTable.getValueAt(fila, 4)));
            update.setDescripcion(String.valueOf(medicoTable.getValueAt(fila, 5)));
            
        }
        
        return update;
    }
    
    private void actualizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarBtnActionPerformed
    
      Medico update;
               update=obtenermedico();
               
        if (nombreTxt.getText().isEmpty()||especialidadTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nombre y Especialidad son requeridos");
            return;
        }
      
        Medico actualizarM=new Medico();
        actualizarM.setId(update.getId());
        actualizarM.setNombre(nombreTxt.getText());
        actualizarM.setEspecialidad(especialidadTxt.getText());
        actualizarM.setEmail(emailTxt.getText());
        actualizarM.setTelefono(telefonoTxt.getText());
        actualizarM.setDescripcion(descripcionTxt.getText());
        
        MedicoController updatem=new MedicoController();
        updatem.Actualizar(actualizarM);
        this.setVisible(false);
        
        
        
    }//GEN-LAST:event_actualizarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarBtn;
    private javax.swing.JLabel descricpcionLbl;
    private javax.swing.JTextField descripcionTxt;
    private javax.swing.JButton editarBtn;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel especialidadLbl;
    private javax.swing.JTextField especialidadTxt;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable medicoTable;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JLabel telefonoLbl;
    private javax.swing.JTextField telefonoTxt;
    private javax.swing.JLabel tituloLbl;
    // End of variables declaration//GEN-END:variables


}
