/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Encapsulamiento.Usuario;
import Negocios.UserController;
import javax.swing.JOptionPane;
import javax.swing.JTextField;






/**
 *
 * @author jmcito
 */
public class UserPerfil extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserPerfil
     */
    public UserPerfil() {
        initComponents();


  }

 




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        usarioLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        tituloLbl = new javax.swing.JLabel();
        none1Lbl = new javax.swing.JLabel();
        none2Lbl = new javax.swing.JLabel();
        none3Lbl = new javax.swing.JLabel();
        passencripLbl = new javax.swing.JLabel();
        dataLbl = new javax.swing.JLabel();
        nombredLbl = new javax.swing.JLabel();
        emaildLbl = new javax.swing.JLabel();
        passworddlbl = new javax.swing.JLabel();
        editarLbl = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Perfil");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreLbl.setForeground(new java.awt.Color(254, 254, 254));
        nombreLbl.setText("Nombre");
        getContentPane().add(nombreLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 68, -1, -1));

        emailLbl.setForeground(new java.awt.Color(254, 254, 254));
        emailLbl.setText("Email");
        getContentPane().add(emailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 96, -1, -1));

        usarioLbl.setForeground(new java.awt.Color(254, 254, 254));
        usarioLbl.setText("Usuario");
        getContentPane().add(usarioLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 119, -1, -1));

        passwordLbl.setForeground(new java.awt.Color(254, 254, 254));
        passwordLbl.setText("Pasword");
        getContentPane().add(passwordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 148, -1, -1));

        tituloLbl.setForeground(new java.awt.Color(254, 254, 254));
        tituloLbl.setText("Perfil de Usuario");
        getContentPane().add(tituloLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 0, -1, -1));

        none1Lbl.setForeground(new java.awt.Color(254, 254, 254));
        none1Lbl.setText("none");
        getContentPane().add(none1Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 68, -1, -1));

        none2Lbl.setForeground(new java.awt.Color(254, 254, 254));
        none2Lbl.setText("none");
        getContentPane().add(none2Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 96, -1, -1));

        none3Lbl.setForeground(new java.awt.Color(254, 254, 254));
        none3Lbl.setText("none");
        getContentPane().add(none3Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 119, -1, -1));

        passencripLbl.setForeground(new java.awt.Color(254, 254, 254));
        passencripLbl.setText("**********");
        getContentPane().add(passencripLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 148, -1, -1));

        dataLbl.setForeground(new java.awt.Color(254, 254, 254));
        dataLbl.setText("Datos");
        getContentPane().add(dataLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 43, -1, -1));

        nombredLbl.setForeground(new java.awt.Color(254, 254, 254));
        nombredLbl.setText("Nombre");
        getContentPane().add(nombredLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 68, -1, -1));

        emaildLbl.setForeground(new java.awt.Color(254, 254, 254));
        emaildLbl.setText("Email");
        getContentPane().add(emaildLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 101, -1, -1));

        passworddlbl.setForeground(new java.awt.Color(254, 254, 254));
        passworddlbl.setText("Password");
        getContentPane().add(passworddlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 134, -1, -1));

        editarLbl.setForeground(new java.awt.Color(254, 254, 254));
        editarLbl.setText("Editar Datos");
        getContentPane().add(editarLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 12, -1, -1));
        getContentPane().add(nombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 63, 228, -1));
        getContentPane().add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 96, 228, -1));
        getContentPane().add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 129, 228, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 183, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 183, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void Mostrar(String perfil) {

        UserController userp=new UserController();
        Usuario Uperfil=userp.MostrarUsuario(perfil);
        none1Lbl.setText(Uperfil.getNombre());
        none2Lbl.setText(Uperfil.getEmail());
        none3Lbl.setText(Uperfil.getUsuario());
        
        
    }
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        UserController userp=new UserController();
        Usuario Userc=userp.MostrarUsuario(none3Lbl.getText());
        int Id=Userc.getId();
        String user=Userc.getUsuario();
        JTextField [] campos=new JTextField[3];
        campos[0]=nombreTxt;
        campos[1]=emailTxt;
        campos[2]=passwordTxt;
        for (JTextField campo : campos) {
            if (campo.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Uno o más campos estan vacios");
                return;
            }
        }
        
        Usuario update=new Usuario();
        update.setId(Id);
        update.setNombre(nombreTxt.getText());
        update.setEmail(emailTxt.getText());
        update.setUsuario(user);
        update.setPassword(passwordTxt.getText());
        
                
          UserController updateUser=new UserController();
          updateUser.EditarUser(update);
          this.setVisible(false);
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        JTextField[] campos=new JTextField[3];
        campos[0]=nombreTxt;
        campos[1]=emailTxt;
        campos[2]=passwordTxt;
        for (JTextField campo : campos) {
            campo.setText(null);
        }
        
        int dialogresult=JOptionPane.showConfirmDialog(null, "¿Desea cancelar?","Aviso",JOptionPane.YES_NO_OPTION);
        if (dialogresult==0) {
            this.setVisible(false);
        }
        
        
    }//GEN-LAST:event_btnCancelarActionPerformed

 
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel dataLbl;
    private javax.swing.JLabel editarLbl;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel emaildLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nombreLbl;
    public static javax.swing.JTextField nombreTxt;
    private javax.swing.JLabel nombredLbl;
    private javax.swing.JLabel none1Lbl;
    private javax.swing.JLabel none2Lbl;
    private javax.swing.JLabel none3Lbl;
    private javax.swing.JLabel passencripLbl;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JLabel passworddlbl;
    private javax.swing.JLabel tituloLbl;
    private javax.swing.JLabel usarioLbl;
    // End of variables declaration//GEN-END:variables

    
    }